var lanI18n = {};
lanI18n["en"] = {
	"userName" : "User Name",
	"password" : "Password",
	"roleName" : "Role Name",
	"desc" : "Description",
	"status" : "Status",
	"verifyUser":"Verify User",
	"enable":"Enable",
	"unable":"Unable",
	"select":"Select",
	"addUser":"Add User",
	"roleName":"Role Name",
	"roleDesc":"Role Description",
	"enterRole":"Please enter Role Name",
	"enterName":"Please enter Name",
	"enterPwd":"Please enter Password",
	"pwdDiff":"The password is different",
	"opSuccess":"Operate Success",
	"opFailed":"Operate Failed",
	"choseRow":"Please chose row",
	"choseRole":"Please chose role",
	"choseMenu":"Please chose menu",
	"roleLoadFail":"Role load fail",
	"menuId":"menuId",
	"menuName":"Menu Name",
	"menuUrl":"Menu Url",
	"menuPid":"Menu Pid",
	"icon":"Icon",
	"addRoleMenu":"Add Role Menu",
};